### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by philemongloblehi** [CedrickOka/pagination-bundle#1]
Hello,

Attached is a screenshot of the error that occurs when I install the bundle in my project.

Technical Specification:
- Language: Php 7
- Framework: Symfony 4

Thank you

![Screenshot from 2020-10-16 16-28-50](https://user-images.githubusercontent.com/20558479/96297527-8269e100-0fe0-11eb-8873-551ba5b1caf6.png)

**Comment by CedrickOka** [comment]
Hi @philemongloblehi ,

Thank you, your issue have just been corrected you can test in version 5.3.3.
